### PR TITLE
Adding cropping functionality

### PR DESCRIPTION
**Pull request by silverlight513**
On top of adding the cropping functionality, I've also upgraded jimp to its latest version (0.5.6).

### CODE REVIEW

**Comment by silverlight513** [comment]
@nitin42 @Sunshine168 
Is this project still maintained? There's some more functionality I'd like to add to on top of this

**Comment by Sunshine168** [comment]
Yes , i will check your PR soon,  PR is always appreciated . Next time you can ping me

**Comment by Sunshine168** [comment]
Did you mind upgrade jimp version in package.json  and add the crop method in doc  too?

**Comment by silverlight513** [comment]
I'll get onto that now. I forgot to go back and add that in now. I might have also found a bug I want to look into

**Comment by silverlight513** [comment]
@Sunshine168 What is the reason behind adding the width and height to the img tag when rendering the `<ProcessImage />` as a style attribute? I found that when cropping it stops the image rendering to the correct size.

**Comment by Sunshine168** [comment]
After using resize it should be the actual  width and height

**Comment by silverlight513** [comment]
I think I need to do some more digging into how resize works because it's stopping the cropping from looking like it's worked properly.

**Comment by silverlight513** [comment]
I've added the changes you asked for but can you hold off merging until I've found out the problem I'm having with width and height as its a bug

**Comment by Sunshine168** [comment]
Ok after finish you can ping me ,  actually show the jpg for how it work is appreciated for me

**Comment by silverlight513** [comment]
@Sunshine168, would it be possible to get a 1.4.0 release with this included sometime soon?

**Comment by Sunshine168** [comment]
@silverlight513  have been release in 1.3.11

**Comment by silverlight513** [comment]
@Sunshine168 Thanks for the release. Just out of curiosity, why does this project choose not to follow semver?

**Comment by Sunshine168** [comment]
Sorry about that ,  released version is 1.3.12 .   You have any question ,just open an issue to talk about it

**Pull request merged**
