### PR TITLE
Added re-render

### PR DESCRIPTION
**Pull request by Sunshine168**
emmm,  btw i found out two points

*  comments only in with-comments branch ~, but thought comments should be in master will be better . or i will add comments in comments branch

* Seem my workspace format the code

### CODE REVIEW

**Comment by nitin42** [comment]
Thanks! Can you show me a gif of this ? would be much better to interpret the results.

**Comment by Sunshine168** [comment]
imgpro

gif is showing  process in worker . And i keeping thinking how to improve experience for this feature

And i updated the demo  in public folder

**Comment by nitin42** [comment]
Exciting!

**Comment by nitin42** [comment]
I'll review your PR sometime later today or may be tomorrow (just a little busy with some other work). Awesome job!

Thanks!

**Comment by Sunshine168** [comment]
okay !

**Comment by Sunshine168** [comment]
~ hi  any news ?

**Comment by Sunshine168** [comment]
BTW i am interesting be  a maintainers for this lib

**Comment by nitin42** [comment]
Added you as a collaborator on this project. Thank you so much for your contributions!

**Comment by Sunshine168** [comment]
🤣 Glad to hear that

**Comment by Sunshine168** [comment]
Hi @nitin42  I plan to add unit test  for this feat  and publish a new version . What is a good way for  i to  contact you , using email or twitter ?   And did you having some work about #8

**Pull request merged**
